siteweb/urls.py
from django.urls import path

from siteweb import views
from django.conf.urls.static import static
from django.conf import settings

# Gestion du routing décidant quelle fonction va traiter telle requête HTTP.

# Règles de matching intégré dans la variable urlpatterns
urlpatterns = [
    path('', views.accueil, name='index'),
    path('accueil/', views.accueil, name='accueil'),
    path('chronologie/', views.chronologie, name='chronologie'),
    path('cnn/', views.cnn, name='cnn'),
    path('rnn/', views.rnn, name='rnn'),
    path('image/', views.image, name='image'),
    path('image/predictImage', views.predictImage, name='predictImage'),
    path('texte/', views.texte, name='texte'),
    path('video/', views.video, name='video'),
    path('audio/', views.audio, name='audio'),

    # URLs de gestion du Blog
    path('posts/', views.post_list, name='home'),
    path('posts/<str:category_name>/', views.post_list, name='post-list'),
    path('posts/detail/<int:post_id>/', views.post_detail, name='post-detail'),

    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
]
# Ajout de l'emplacement du dossier MEDIA, un dossier où seront enregistrés des images envoyées par l'utilisateur
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sitewebdnn/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('site/', include('siteweb.urls')),
    path('', include('siteweb.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

siteweb/models.py
from django.db import models
from django.template.defaultfilters import slugify
from ckeditor_uploader.fields import RichTextUploadingField

# Ce fichier gère la création de modèles de données via une classe de représentation des données que l'on souhaite
# manipuler et stocker dans une base de données. Une classe assure ainsi l'ajout et la synchronisation
# des tables de base données.

# Un modèle = une classe = une table
# chaque attribut d'une classe représente une colonne d'une table

class PostCategory(models.Model):
    # La classe Postcategory héritant de models.Model
    name = models.CharField(max_length=50)
    # PostCategory est uniquement défini par un nom

    # slugify() transforme une catégorie en URL valide en remplaçant les espaces par un tiret
    # ainsi que les majuscules en minuscules
    def slug(self):
        return slugify(self.name)

    def __str__(self):
        # Surcharge de la méthode __str__
        return self.name
        # retourne le nom de la catégorie

class Post(models.Model):
    # La classe Posts héritant de models.Model
    title = models.CharField(max_length=100)
    category = models.ForeignKey('PostCategory',
    # Une clé étrangère vers PostCategory, suivi de la configuration possible :
                                 null=True,
                                 # Autorise le fait d'avoir une valeur nulle
                                 blank=True,
                                 # Autorise le fait d'avoir une chaîne vide
                                 on_delete=models.DO_NOTHING)
                                 # Lors de la suppression ne rien faire

    published = models.BooleanField(default=False)
    # le statu publié ou non du post, sachant que par défaut un post n'est pas publié (default = False)
    text = RichTextUploadingField()
    #  La mise en forme de la partie message du post est enrichie à l'aide du package ckeditor
    created_at = models.DateTimeField(auto_now_add=True)
    # Enregistrement de la date de création du post

    def __str__(self):
        return self.title
        # Retourne le titre

siteweb/forms.py
from django import forms


# un pattern Django form simplifie la génération et le traitement des formulaires HTML

# Chaque attribut correspond à un input attendu dans un formulaire et dont le type déterminera le rendu
# Une foi que la classe est définir il suffit d'injecter une instance de ce form dans un template
# et Django se changera du rendu, de la vérification d'erreurs côté client et de la vérification d'erreurs côté serveur
# au moment de la récupération des informations et du traitement du formulaire.

class ContactForm(forms.Form):
    # Une classe héritant de forms.Form
    from_email = forms.EmailField(required=True)
    # L'attribut email
    subject = forms.CharField(required=True)
    # L'attribut sujet du formulaire
    message = forms.CharField(widget=forms.Textarea, required=True)
    # L'attribut dédié au message

siteweb/views.py
from django.shortcuts import get_object_or_404
from siteweb.models import Post
from siteweb import model_helpers
from siteweb import navigation
from django.core.files.storage import FileSystemStorage
from django.core.mail import send_mail, BadHeaderError
from django.shortcuts import render
from .forms import ContactForm
from django.conf import settings
from django.contrib import messages

import requests
import urllib
import json

# Le fichier views.py contient les fonctions générant les réponses HTTP à renvoyer au navigateur de l'utilisateur
# La liste des fonctions qui seront appelées par le module de routing (définit dans le fichier urls.py)

def accueil(request):
    # La fonction associée à la rubrique accueil de la barre de navigation
    context = {
        'navigation_items': navigation.navigation_items(navigation.NAV_ACCUEIL),
    }

    return render(request, 'site/accueil.html', context)
    # Retourne le contexte et l'emplacement du fichier accueil.html


def chronologie(request):
    # La fonction associée à la rubrique chronologie de la barre de navigation
    context = {
        'navigation_items': navigation.navigation_items(navigation.NAV_CHRONOLOGIE),
    }

    return render(request, 'site/chronologie.html', context)
    # Retourne le contexte et l'emplacement du fichier chronologie.html

def cnn(request):
    # La fonction associée à la rubrique cnn de la barre de navigation
    context = {
        'navigation_items': navigation.navigation_items(navigation.NAV_CNN),
    }

    return render(request, 'site/cnn.html', context)
    # retourne le contexte et l'emplacement du fichier cnn.html

def rnn(request):
    # La fonction associée à la rubrique rnn de la barre de navigation
    context = {
        'navigation_items': navigation.navigation_items(navigation.NAV_RNN),
    }

    return render(request, 'site/rnn.html', context)
    # Retourne le contexte et l'emplacement du fichier rnn.html


def post_list(request, category_name=model_helpers.post_category_all.slug()):
    # La fonction associée à la rubrique blog de la barre de navigation et dédiée à l'affichage de l'ensemble des posts
    category, posts = model_helpers.get_category_and_posts(category_name)
    # récupère la catégorie et les posts à afficher suivant leur sélection par l'utilisateur
    categories = model_helpers.get_categories()
    # Récupère les catégories à afficher sur la partie droite du blog

    context = {
        'navigation_items': navigation.navigation_items(navigation.NAV_POSTS),
        # L'objet Blog de la barre de navigation
        'category': category,
        # La catégorie
        'posts': posts,
        # Le ou les pots
        'categories': categories,
        # L'ensemble des catégories à afficher pour sélection
    }

    return render(request, 'site/post_list.html', context)
    # Retourne le contexte et l'emplacement du fichier post_list.html

def post_detail(request, post_id):
    # La fonction associée à la rubrique blog de la barre de navigation et dédiée à l'affichage d'un seul post
    post = get_object_or_404(Post, pk=post_id)
    # Récupérer le post ou une erreur à partir de son identifiant dans la table de base de données Post
    posts_same_category = Post.objects.filter(published=True, category=post.category) \
        .exclude(pk=post_id)
    # Récupérer les posts publiés d'une même catégorie

    context = {
        'navigation_items': navigation.navigation_items(navigation.NAV_POSTS),
        # L'objet Blog de la barre de navigation
        'post': post,
        # Le post
        'posts_same_category': posts_same_category,
        # Les posts de même catégories

    }

    return render(request, 'site/post_detail.html', context)
    # Retourne le contexte et l'emplacement du fichier post_detail.html


def image(request):
    # La fonction associée à la rubrique Application Image de la barre de navigation
    context = {
        'navigation_items': navigation.navigation_items(navigation.NAV_IMAGE),
        # L'objet Image de la barre de navigation
    }

    return render(request, 'site/application_image.html', context)
    # Retourne le contexte et l'emplacement du fichier application_image.html


def predictImage(request):
    # La fonction associée à la rubrique Application Image de la barre de navigation assurant la prédiction d'une image
    fileobj = request.FILES['filePath']
    # Recupérer l'emplacement de l'image
    #print("fileobj")
    #print(fileobj)
    fs = FileSystemStorage()
    filePathName = fs.save(fileobj.name, fileobj)
    # Enregistrer l'image dans le dossier media du serveur web
    filePathName = fs.url(filePathName)
    testimage = '.' + filePathName
    #print("testimage")
    #print(testimage)
    api = settings.URL_TUMOR_API
    upload = {
        'picture': open(testimage, 'rb')
    }
    response = requests.post(api, files=upload)
    # Envoyer l'image à l'API
    data = response.json()
    # Réponse de l'API proposant les résultats de la prédiction


    context = {
        'vgg_prediction': data['vgg_tumor_pred'],
        # Le résultat de la prédiction du modèle VGG
        'resnet_prediction': data['resnet_tumor_pred'],
        # Le résultat de la prédiction du modèle resnet
        'inception_resnet_v2_prediction': data['inception_resnet_v2_tumor_pred'],
        # Le résultat de la prédiction du modèle inception resnet V2
        'navigation_items': navigation.navigation_items(navigation.NAV_IMAGE),
        # L'objet Image de la barre de navigation
    }
    return render(request, 'site/application_image.html', context)
    # Retourne le contexte et l'emplacement du fichier application_image.html


def texte(request):
    # La fonction associée à la rubrique Application Texte de la barre de navigation
    context = {
        'navigation_items': navigation.navigation_items(navigation.NAV_TEXTE),
    }
    # L'objet Texte de la barre de navigation

    return render(request, 'site/application_texte.html', context)
    # retourne le contexte et l'emplacement du fichier application_texte.html

def video(request):
    # La fonction associée à la rubrique Application Vidéo de la barre de navigation
    context = {
        'navigation_items': navigation.navigation_items(navigation.NAV_VIDEO),
    }
    # L'objet Vidéo de la barre de navigation

    return render(request, 'site/application_video.html', context)
    # Retourne le contexte et l'emplacement du fichier application_video.html


def audio(request):
    # La fonction associée à la rubrique Application Audio de la barre de navigation
    context = {
        'navigation_items': navigation.navigation_items(navigation.NAV_AUDIO),
    }
    # L'objet audio de la barre de navigation

    return render(request, 'site/application_audio.html', context)
    # Retourne le contexte et l'emplacement du fichier application_audio.html


def about(request):
    # La fonction associée à la rubrique À Propos de la barre de navigation
    context = {
        'navigation_items': navigation.navigation_items(navigation.NAV_ABOUT),
    }
    # Lo'bjet about de la barre de navigation

    return render(request, 'site/about.html', context)
    # Retourne le contexte et l'emplacement du fichier about.html


def contact(request):
    # La fonction associée à la rubrique À Propos de la barre de navigation
    context = {
        'navigation_items': navigation.navigation_items(navigation.NAV_CONTACT),
        # L'objet Contact de la barre de navigation
    }
    if request.method == 'POST':
        # Si la méthode est de type POST
        form = ContactForm(request.POST)
        # récupérer l'objet form
        if form.is_valid():
            # si l'objet est valide
            from_email = form.cleaned_data['from_email']
            # Récupérer l'e-mail d'envoi
            subject = form.cleaned_data['subject']
            # Récupérer le sujet du mail
            message = form.cleaned_data['message']
            # Récupérer le message du mail
            message = "De : " + str(from_email) + " - " + str(message)
            # Ajouter l'adresse du mail de l'émetteur dans le mail reçu par l'administration
            ''' Begin reCAPTCHA validation '''
            recaptcha_response = request.POST.get('g-recaptcha-response')
            # Retour du recaptcha
            url = settings.URL_GOOGLE_API
            # Enregistrer dans la variable url, l'adresse de l'API Google du recaptcha
            values = {
                'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
                # La clé secrète
                'response': recaptcha_response
                # la réponse
            }
            data = urllib.parse.urlencode(values).encode()
            # urllib.parse.urlencode convertir le dictionnaire value en chaîne de requête.
            req = urllib.request.Request(url, data=data)
            # Envoi de la requète à l'API Google
            response = urllib.request.urlopen(req)
            # retour de la réponse
            result = json.loads(response.read().decode())
            ''' End reCAPTCHA validation '''
            # Résultat de la réponse
            if result['success']:
                # le résultat est correct
                try:
                    send_mail(subject, message, from_email, ['patriceblanchard.perso@gmail.com'])
                    # Le sujet, le mail et le mail est envoyé à l'adresse mail 'patriceblanchard.perso@gmail.com'
                except BadHeaderError:
                    return render(request, "site/contact_error.html", context)
                    # en cas d'erreur, la page contact_error le signale
                return render(request, "site/contact_success.html", context)
                # en cas de réussite, la page contact_success spécifie que le mail a bien été envoyé
            else:
                messages.error(request, 'Invalid reCAPTCHA. Please try again.')
                # sinon le recaptcha présente un problème
                form = ContactForm()

siteweb/templates/site/about.html
{% extends 'base.html' %}
{% load static %}

{% block title %} À propos {% endblock %}

{% block content %}
<div class="col-12">
    <br>
    <br>
    <h3>Patrice Blanchard</h3>
    <hr>
    <div class="row">
        <div class="col-md-9">
            <p>
                Étudiant à l'institut d'enseignement à distance de l'université Paris 8.
                <br>
                <br>
                Licence Informatique / Psychologie.
                <br>
                <br>
                La création de ce site web dédié au <span class="fst-italic">deep Learning</span> s'insère dans le cadre
                d'un projet de licence 2.
            </p>
            <br>
            <p>
                Les dernières avancées technologiques en lien avec le <span class="fst-italic">deep learning</span> ont
                connu une évolution sans précédent ces dernières années. En effet, de nouvelles combinaisons et/ou
                optimisations d'architectures sont proposées lors de défis réunissant de nombreuses équipes de
                recherches, attendues par exemple lors la compétition ImageNet de Reconnaissance Visuelle à Grande
                Échelle organisée tous les ans. De toute évidence, ce site web n'en est qu'à ses débuts, je prévois à
                l'avenir d'agrémenter son contenu d'explications plus détaillées ainsi que de projets de L3 au fil de
                mon apprentissage. Voici les projets qui seront proposés au mois d'avril 2022 :
            <ul>
                <li>Détection de scènes, d'objets dans une vidéo : CNN + GRU;</li>
                <li>Classification de sons - LSTM ou GRU;</li>
                <li>Web scraping associé à MongoDB  et un réseau de neurones réccurents : LSTM ou GRU.</li>
            </ul>
            </p>
        </div>
        <div class="col-md-3">
            <img src="{% static 'img/a_propos/moi.jpg' %}" class="rounded mx-auto d-block" width="60%">
        </div>
    </div>
</div>

{% endblock content %}

siteweb/templates/site/application_audio.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Application sur des données de type audio {% endblock %}

{% block content %}
<div class="col-12">
    <br>
    <h5>Classification de sons - LSTM ou GRU (prévu pour le mois d'avril)</h5>
</div>

{% endblock content %}

siteweb/templates/site/application_texte.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Application de type texte {% endblock %}

{% block content %}
<div class="col-12">
    <br>
    <h5>Web scraping associé à MongoDB  et un réseau de neurones réccurents : LSTM ou GRU (prévu pour le mois d'avril)</h5>
</div>

{% endblock content %}

siteweb/templates/site/application_video.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Application de type vidéo {% endblock %}

{% block content %}
<div class="col-12">
    <br>
    <h5>Détection de scènes, d'objets dans une vidéo : CNN + GRU (prévu pour le mois d'avril)</h5>
</div>

{% endblock content %}

siteweb/templates/site/contact.html
{% extends 'base.html' %}
{% load static %}


{% block title %} Contact {% endblock %}

{% block content %}


<div class="col-12">
    <br>
    <br>
    <div class="row justify-content-center">
        <div class="col-md-9 ">
            <form action="" method="post">
                {% csrf_token %}
                <!--  Mesure de sécurité créant un identifiant unique au formulaire -->
                <tr>
                    <th>
                        <label for="id_email">Email:</label>
                    </th>
                    <td>
                        <input type="email" name="from_email" maxlength="254" required id="id_email">
                    </td>
                </tr>
                <tr>
                    <th>
                        <label for="id_subject">Sujet :</label>
                    </th>
                    <td>
                        <input type="text" name="subject" maxlength="255" required id="id_subject">
                    </td>
                </tr>
                <tr>
                    <th>
                        <label for="id_message">Message :</label>
                    </th>
                    <td>
                        <textarea name="message" cols="40" rows="10" required id="id_message"></textarea>
                    </td>
                </tr>
                <script src='https://www.google.com/recaptcha/api.js'></script>

                <div class="col-md-12">
                    <div class="g-recaptcha" data-sitekey="6LcGUqseAAAAAGwMVcW52RQiG_cz3gjknHpXNc9g"></div>
                </div>
                <br>
                <input type="submit" value="Envoyer">
            </form>
        </div>
    </div>
</div>

{% endblock content %}

siteweb/templates/site/contact_error.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Contact - Page d'erreur {% endblock %}

{% block content %}

<p class="text-center fw-bold">
    <br>
    <br>
    Erreur : le message n'a pas pu être envoyé.
</p>
{% endblock content %}

siteweb/templates/site/contact_success.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Contact - Envoi réussi {% endblock %}

{% block content %}

<p class="text-center fw-bold">
    <br>
    <br>
    Merci pour votre message, celui-ci a été envoyé avec succès.
</p>
{% endblock content %}

siteweb/templates/site/post_detail.html
{% extends 'base.html' %}

{% block title %}{{ post.title }} {% endblock %}

{% block content %}
<div class="col-sm-9">
    <div class="mt-3">
        <h2>{{ post.title }}</h2>
        <small>Posted on {{ post.created_at }}</small>
        <hr>

        <p class="text-muted">
            {{ post.text|safe }}
        </p>
        <a href="{% url 'post-list' post.category.slug %}"
           class="badge bg-secondary">{{ post.category.name|capfirst }}</a>
    </div>
</div>
<div class="col-sm-3">
    <h5>Posts venant de la même catégorie</h5>
    <ul class="list-group">
        {% for post in posts_same_category %}
        <li class="list-group-item">
            <a href="{% url 'post-detail' post.pk %}">{{ post.title|truncatewords:4 }}</a>
        </li>
        {% empty %}
        C'est le premier post !
        {% endfor %}
    </ul>
</div>
{% endblock content %}

siteweb/templates/site/post_list.html
{% extends 'base.html' %}
{% block title %}Posts{% endblock %}

{% block content %}

<div class="col-md-10">
</br>
    {% for post in posts %}
    <div class="mb-4">
        <h5><a href="{% url 'post-detail' post.pk %}" class="text-reset"> {{ post.title }}</a></h5>
        <small>Posté le {{ post.created_at }}</small>
        <hr>
        <p class="text-justify">
            {{ post.text|safe|truncatewords:50 }}
            <a href="{% url 'post-detail' post.pk %}" class="text-reset">[Lire plus]</a>
        </p>
        <a href="{% url 'post-list' post.category.slug %}" class="badge bg-secondary">
            {{ post.category.name|capfirst }}
        </a>
    </div>

    {% empty %}
    <!-- Gestion d'une page associé à une catégorie inexistante -->
    <div class="text-center">
        <p class="display-1">:-(</p>
        <h3 class="mt-4">
            Sorry, no posts for the category <span class="badge bg-secondary"> {{ category.name }} </span>
        </h3>
    </div>
    {% endfor %}
</div>

<div class="col-md-2">
    </br>
    <h5>Categories</h5>
    <ul class="list-unstyled">
        {% for cat in categories %}
        <li>
            <a href="{% url 'post-list' cat.slug %}"
               class="badge bg-secondary">
                {{ cat.name|capfirst }}
            </a>
        </li>
        {% endfor %}
    </ul>
</div>


{% endblock content %}

siteweb/templates/site/rnn.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Réseau de neurones récurrents {% endblock %}

{% block content %}
<div class="col-12">
    <br>
    <br>
    <h5>Composition d'un réseau de neurones récurrents : LSTM et GRU (prévu pour le mois d'avril)</h5>
</div>

{% endblock content %}